name: Run Python Script from ECR Image

on:
  push:
    branches:
      - main  # Adjust this as needed

jobs:
  run-ecr-job:
    runs-on: ubuntu-latest
    
    container:
      image: https://gallery.ecr.aws/f6e2z3b0/fornax-images
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: print python
      run: which python

    - name: Run Python script
      run: python /github/workspace/run.py
