name: Run Python Script from ECR Image

on:
  push:
    branches:
      - main  # Adjust this as needed

jobs:
  run-ecr-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull Docker image from public ECR
      run: |
        docker pull public.ecr.aws/f6e2z3b0/fornax-images:base_image-latest
    - name: Run Python script inside Docker container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          public.ecr.aws/f6e2z3b0/fornax-images:base_image-latest \
          which python
